# Generated by Django 4.2.3 on 2023-07-25 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
